/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'error': '#ba1a1a',
        'secondary-fixed': '#7dfbae',
        'surface-container-high': '#e8e8e8',
        'on-tertiary-container': '#8fd6ff',
        'outline-variant': '#d9c2b9',
        'on-tertiary-fixed-variant': '#004c69',
        'error-container': '#ffdad6',
        'surface-dim': '#dadada',
        'surface-variant': '#e2e2e2',
        'surface-container': '#eeeeee',
        'outline': '#86736c',
        'on-surface': '#1a1c1c',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#7ad0ff',
        'tertiary-container': '#005e80',
        'on-primary': '#ffffff',
        'primary-fixed': '#ffdbcd',
        'surface-bright': '#f9f9f9',
        'on-surface-variant': '#53433d',
        'on-primary-fixed': '#360f00',
        'inverse-on-surface': '#f1f1f1',
        'on-tertiary-fixed': '#001e2c',
        'surface': '#f9f9f9',
        'on-primary-container': '#ffbfa4',
        'on-secondary-fixed-variant': '#00522d',
        'on-secondary-container': '#007442',
        'surface-tint': '#8e4d2f',
        'on-background': '#1a1c1c',
        'primary-fixed-dim': '#ffb596',
        'on-secondary-fixed': '#00210f',
        'secondary-container': '#7dfbae',
        'primary': '#683014',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#71361b',
        'primary-container': '#854629',
        'tertiary-fixed': '#c3e8ff',
        'secondary-fixed-dim': '#5fde94',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#2f3131',
        'secondary': '#006d3e',
        'background': '#f9f9f9',
        'inverse-primary': '#ffb596',
        'surface-container-highest': '#e2e2e2',
        'tertiary': '#00455f',
        'surface-container-low': '#f3f3f3',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
};